import type { IpaSound } from "./types";

export const IPA_SOUNDS: IpaSound[] = [
  // ==================== NGUYÊN ÂM ĐƠN (12 MONOPHTHONGS) ====================
  {
    id: "i-long",
    symbol: "/iː/",
    name: "Long E",
    vietnameseName: "Âm i dài",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn dài",
    phoneticProperties: {
      length: "long",
      voicing: "voiced",
      tonguePosition: "Trước (Front)",
      jawOpening: "Hẹp / Khép (Close)",
      lipShape: "Môi dẹt rộng như đang mỉm cười",
      summary: "Nguyên âm đơn dài, lưỡi nâng cao về phía trước, hai khóe môi kéo sang hai bên.",
    },
    articulation: {
      steps: [
        "Mở môi hẹp, hai khóe môi kéo nhẹ sang hai bên như đang mỉm cười nhẹ.",
        "Nâng phần trước thân lưỡi lên cao gần vòm miệng hard palate.",
        "Phát ra âm /iː/ kéo dài khoảng 1 giây, luồng hơi và dây thanh rung liên tục.",
      ],
      commonMistakes: [
        "Phát âm quá ngắn giống âm /ɪ/ trong 'ship'.",
        "Thả lỏng cơ môi quá sớm khiến âm bị biến dạng thành âm đôi.",
      ],
      selfCheckTip: "Đặt hai ngón tay ở khóe môi, bạn sẽ cảm nhận cơ môi căng dẹt ngang khi đọc /iː/.",
    },
    examples: [
      { word: "see", ipa: "/siː/", translation: "nhìn thấy", position: "final", highlightedLetters: "ee" },
      { word: "sheep", ipa: "/ʃiːp/", translation: "con cừu", position: "medial", highlightedLetters: "ee" },
      { word: "teacher", ipa: "/ˈtiː.tʃər/", translation: "giáo viên", position: "initial", highlightedLetters: "ea" },
      { word: "piece", ipa: "/piːs/", translation: "mảnh, miếng", position: "medial", highlightedLetters: "ie" },
      { word: "receive", ipa: "/rɪˈsiːv/", translation: "nhận được", position: "medial", highlightedLetters: "ei" },
    ],
    spellingPatterns: [
      { letters: "ee", examples: ["see", "feel", "meet", "tree"] },
      { letters: "ea", examples: ["read", "team", "eat", "sea"] },
      { letters: "ie", examples: ["piece", "achieve", "field"] },
      { letters: "e_e / e", examples: ["these", "me", "he", "be"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "sheep", ipa: "/ʃiːp/", translation: "con cừu" },
        confusedWord: { word: "ship", ipa: "/ʃɪp/", translation: "con tàu" },
        confusedSoundSymbol: "/ɪ/",
      },
      {
        targetWord: { word: "feet", ipa: "/fiːt/", translation: "đôi chân" },
        confusedWord: { word: "fit", ipa: "/fɪt/", translation: "vừa vặn" },
        confusedSoundSymbol: "/ɪ/",
      },
    ],
  },
  {
    id: "i-short",
    symbol: "/ɪ/",
    name: "Short I",
    vietnameseName: "Âm i ngắn",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn ngắn",
    phoneticProperties: {
      length: "short",
      voicing: "voiced",
      tonguePosition: "Gần phía trước (Near-front)",
      jawOpening: "Hơi khép (Near-close)",
      lipShape: "Môi hơi mở, thả lỏng tự nhiên",
      summary: "Nguyên âm đơn ngắn, cơ môi và lưỡi thả lỏng hơn /iː/.",
    },
    articulation: {
      steps: [
        "Môi mở hơi khép, thả lỏng cơ mặt hoàn toàn (không dẹt môi như /iː/).",
        "Đưa lưỡi lên cao vừa phải, hơi lùi về sau một chút so với /iː/.",
        "Phát âm dứt khoát, bật hơi ngắn gọn trong khoảng 0.3 giây.",
      ],
      commonMistakes: [
        "Phát âm thành âm 'i' tiếng Việt quá dài hoặc căng cơ môi như /iː/.",
        "Nhầm sang âm /e/ ('set' thay vì 'sit').",
      ],
      selfCheckTip: "Âm /ɪ/ rất ngắn, giật nhẹ bụng khi bật âm.",
    },
    examples: [
      { word: "sit", ipa: "/sɪt/", translation: "nhiều", position: "medial", highlightedLetters: "i" },
      { word: "ship", ipa: "/ʃɪp/", translation: "con tàu", position: "medial", highlightedLetters: "i" },
      { word: "city", ipa: "/ˈsɪt.i/", translation: "thành phố", position: "initial", highlightedLetters: "i" },
      { word: "busy", ipa: "/ˈbɪz.i/", translation: "bận rộn", position: "medial", highlightedLetters: "u" },
    ],
    spellingPatterns: [
      { letters: "i", examples: ["sit", "big", "hit", "milk"] },
      { letters: "y (cuối từ)", examples: ["happy", "city", "busy"] },
      { letters: "ui", examples: ["build", "guitar"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "sit", ipa: "/sɪt/", translation: "ngồi" },
        confusedWord: { word: "seat", ipa: "/siːt/", translation: "chỗ ngồi" },
        confusedSoundSymbol: "/iː/",
      },
    ],
  },
  {
    id: "u-short",
    symbol: "/ʊ/",
    name: "Short U",
    vietnameseName: "Âm u ngắn",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn ngắn",
    phoneticProperties: {
      length: "short",
      voicing: "voiced",
      tonguePosition: "Gần phía sau (Near-back)",
      jawOpening: "Hơi khép (Near-close)",
      lipShape: "Môi hơi tròn nhẹ, thả lỏng",
      summary: "Nguyên âm đơn ngắn, môi hơi tròn thả lỏng, phát âm ngắn gọn.",
    },
    articulation: {
      steps: [
        "Môi hơi nhô ra trước và chu nhẹ nhưng thả lỏng (không nhọn môi như /uː/).",
        "Cuống lưỡi nâng lên gần ngạc mềm.",
        "Bật âm ngắn dứt khoát.",
      ],
      commonMistakes: ["Đọc thành 'u' tiếng Việt dài hoặc chu môi quá chặt."],
      selfCheckTip: "Cơ môi thả lỏng, âm phát ra nằm giữa 'u' và 'ơ'.",
    },
    examples: [
      { word: "book", ipa: "/bʊk/", translation: "sách", position: "medial", highlightedLetters: "oo" },
      { word: "put", ipa: "/pʊt/", translation: "đặt, để", position: "medial", highlightedLetters: "u" },
      { word: "foot", ipa: "/fʊt/", translation: "bàn chân", position: "medial", highlightedLetters: "oo" },
      { word: "could", ipa: "/kʊd/", translation: "có thể", position: "medial", highlightedLetters: "oul" },
    ],
    spellingPatterns: [
      { letters: "oo", examples: ["book", "look", "good", "foot"] },
      { letters: "u", examples: ["put", "full", "push"] },
      { letters: "ould", examples: ["could", "would", "should"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "pull", ipa: "/pʊl/", translation: "kéo" },
        confusedWord: { word: "pool", ipa: "/puːl/", translation: "hồ bơi" },
        confusedSoundSymbol: "/uː/",
      },
    ],
  },
  {
    id: "u-long",
    symbol: "/uː/",
    name: "Long U",
    vietnameseName: "Âm u dài",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn dài",
    phoneticProperties: {
      length: "long",
      voicing: "voiced",
      tonguePosition: "Sau (Back)",
      jawOpening: "Khép (Close)",
      lipShape: "Môi tròn nhọn, chu ra trước",
      summary: "Nguyên âm đơn dài, môi chu tròn hẹp, luồng hơi kéo dài.",
    },
    articulation: {
      steps: [
        "Chu môi tròn nhỏ nhô ra phía trước như đang thổi sáo.",
        "Cuống lưỡi nâng cao về phía ngạc mềm.",
        "Giữ nguyên khẩu hình và ngân âm kéo dài.",
      ],
      commonMistakes: ["Thả lỏng môi quá nhanh khiến âm thành u ngắn."],
      selfCheckTip: "Môi tròn nhỏ hình chữ O nhỏ xíu.",
    },
    examples: [
      { word: "too", ipa: "/tuː/", translation: "cũng, quá", position: "final", highlightedLetters: "oo" },
      { word: "shoe", ipa: "/ʃuː/", translation: "giày", position: "final", highlightedLetters: "oe" },
      { word: "blue", ipa: "/bluː/", translation: "màu xanh", position: "final", highlightedLetters: "ue" },
      { word: "food", ipa: "/fuːd/", translation: "thức ăn", position: "medial", highlightedLetters: "oo" },
    ],
    spellingPatterns: [
      { letters: "oo", examples: ["food", "moon", "too", "boot"] },
      { letters: "u_e", examples: ["june", "rule", "flute"] },
      { letters: "ew / ue", examples: ["new", "blue", "grew"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "fool", ipa: "/fuːl/", translation: "kẻ ngốc" },
        confusedWord: { word: "full", ipa: "/fʊl/", translation: "đầy" },
        confusedSoundSymbol: "/ʊ/",
      },
    ],
  },
  {
    id: "e-short",
    symbol: "/e/",
    name: "Short E",
    vietnameseName: "Âm e ngắn",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn ngắn",
    phoneticProperties: {
      length: "short",
      voicing: "voiced",
      tonguePosition: "Trước (Front)",
      jawOpening: "Vừa mở (Mid-open)",
      lipShape: "Môi mở rộng hơn âm /ɪ/",
      summary: "Nguyên âm đơn ngắn, hàm mở vừa phải, âm phát ra gọn gàng.",
    },
    articulation: {
      steps: [
        "Hạ hàm xuống vừa phải (rộng hơn âm /ɪ/).",
        "Lưỡi đặt ở phía trước miệng, đầu lưỡi chạm nhẹ răng dưới.",
        "Phát âm ngắn dứt khoát.",
      ],
      commonMistakes: ["Mở miệng quá rộng thành âm /æ/."],
      selfCheckTip: "Khoảng cách giữa hai hàm răng cỡ một ngón tay.",
    },
    examples: [
      { word: "bed", ipa: "/bed/", translation: "giường", position: "medial", highlightedLetters: "e" },
      { word: "pen", ipa: "/pen/", translation: "bút", position: "medial", highlightedLetters: "e" },
      { word: "head", ipa: "/hed/", translation: "đầu", position: "medial", highlightedLetters: "ea" },
      { word: "many", ipa: "/ˈmen.i/", translation: "nhiều", position: "initial", highlightedLetters: "a" },
    ],
    spellingPatterns: [
      { letters: "e", examples: ["bed", "pen", "red", "leg"] },
      { letters: "ea", examples: ["head", "bread", "ready"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "pen", ipa: "/pen/", translation: "bút" },
        confusedWord: { word: "pan", ipa: "/pæn/", translation: "chảo" },
        confusedSoundSymbol: "/æ/",
      },
    ],
  },
  {
    id: "schwa",
    symbol: "/ə/",
    name: "Schwa",
    vietnameseName: "Âm ơ ngắn (Schwa)",
    category: "monophthong",
    typeLabel: "Nguyên âm trung tính ngắn",
    phoneticProperties: {
      length: "short",
      voicing: "voiced",
      tonguePosition: "Giữa (Central)",
      jawOpening: "Vừa (Mid)",
      lipShape: "Môi và lưỡi thả lỏng hoàn toàn",
      summary: "Âm phổ biến nhất tiếng Anh, xuất hiện ở âm tiết không nhấn.",
    },
    articulation: {
      steps: [
        "Thả lỏng hoàn toàn môi, lưỡi và cơ hàm.",
        "Phát âm nhẹ nhàng ngắn gọn 'ơ'.",
      ],
      commonMistakes: ["Phát âm quá rõ hoặc nhấn giọng vào âm schwa."],
      selfCheckTip: "Âm lướt nhẹ, hầu như không tốn sức.",
    },
    examples: [
      { word: "teacher", ipa: "/ˈtiː.tʃər/", translation: "giáo viên", position: "final", highlightedLetters: "er" },
      { word: "about", ipa: "/əˈbaʊt/", translation: "về", position: "initial", highlightedLetters: "a" },
      { word: "banana", ipa: "/bəˈnɑː.nə/", translation: "chuối", position: "initial", highlightedLetters: "a" },
    ],
    spellingPatterns: [
      { letters: "a, e, i, o, u không nhấn", examples: ["about", "open", "doctor", "support"] },
    ],
    minimalPairs: [],
  },
  {
    id: "er-long",
    symbol: "/ɜː/",
    name: "Long ER",
    vietnameseName: "Âm ơ dài",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn dài",
    phoneticProperties: {
      length: "long",
      voicing: "voiced",
      tonguePosition: "Giữa (Central)",
      jawOpening: "Vừa (Mid)",
      lipShape: "Môi hơi mở, thả lỏng",
      summary: "Nguyên âm đơn dài trung tính, luôn xuất hiện ở âm tiết được nhấn.",
    },
    articulation: {
      steps: [
        "Môi thả lỏng, hơi mở vừa.",
        "Lưỡi đặt ở giữa khoang miệng.",
        "Ngân dài âm 'ơơ'.",
      ],
      commonMistakes: ["Đọc quá ngắn thành âm schwa /ə/."],
      selfCheckTip: "Giữ khẩu hình và kéo dài hơi ổn định.",
    },
    examples: [
      { word: "bird", ipa: "/bɜːd/", translation: "con chim", position: "medial", highlightedLetters: "ir" },
      { word: "nurse", ipa: "/nɜːs/", translation: "y tá", position: "medial", highlightedLetters: "ur" },
      { word: "learn", ipa: "/lɜːn/", translation: "học", position: "medial", highlightedLetters: "ear" },
      { word: "work", ipa: "/wɜːk/", translation: "làm việc", position: "medial", highlightedLetters: "or" },
    ],
    spellingPatterns: [
      { letters: "ir", examples: ["bird", "girl", "first"] },
      { letters: "ur", examples: ["turn", "nurse", "burn"] },
      { letters: "er / ear", examples: ["her", "learn", "earth"] },
    ],
    minimalPairs: [],
  },
  {
    id: "or-long",
    symbol: "/ɔː/",
    name: "Long OR",
    vietnameseName: "Âm o dài",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn dài",
    phoneticProperties: {
      length: "long",
      voicing: "voiced",
      tonguePosition: "Sau (Back)",
      jawOpening: "Vừa mở (Mid-open)",
      lipShape: "Môi tròn nhỏ nhô ra trước",
      summary: "Nguyên âm đơn dài, môi tròn chắc, lưỡi lùi về sau.",
    },
    articulation: {
      steps: [
        "Tròn môi nhô ra phía trước.",
        "Lưỡi hạ thấp lùi về phía sau.",
        "Phát âm 'o' kéo dài.",
      ],
      commonMistakes: ["Mở môi không đủ tròn làm âm bị bẹt."],
      selfCheckTip: "Môi tròn chắc căng hơn /ɒ/.",
    },
    examples: [
      { word: "door", ipa: "/dɔːr/", translation: "cửa ra vào", position: "final", highlightedLetters: "oor" },
      { word: "four", ipa: "/fɔːr/", translation: "số 4", position: "final", highlightedLetters: "our" },
      { word: "call", ipa: "/kɔːl/", translation: "gọi", position: "medial", highlightedLetters: "all" },
      { word: "law", ipa: "/lɔː/", translation: "luật", position: "final", highlightedLetters: "aw" },
    ],
    spellingPatterns: [
      { letters: "or / oor", examples: ["fork", "door", "floor"] },
      { letters: "al / aw", examples: ["call", "walk", "law", "saw"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "port", ipa: "/pɔːt/", translation: "cảng" },
        confusedWord: { word: "pot", ipa: "/pɒt/", translation: "nồi" },
        confusedSoundSymbol: "/ɒ/",
      },
    ],
  },
  {
    id: "ae-short",
    symbol: "/æ/",
    name: "Short AE",
    vietnameseName: "Âm e bẹt",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn ngắn",
    phoneticProperties: {
      length: "short",
      voicing: "voiced",
      tonguePosition: "Trước (Front)",
      jawOpening: "Mở rộng (Open)",
      lipShape: "Môi dẹt ngang rộng",
      summary: "Nguyên âm bẹt mở rộng hàm, nằm giữa 'e' và 'a'.",
    },
    articulation: {
      steps: [
        "Hạ thấp hàm dưới mở rộng miệng.",
        "Kéo rộng hai khóe môi sang hai bên.",
        "Đầu lưỡi đè thấp chạm sau răng cửa dưới, bật âm dứt khoát.",
      ],
      commonMistakes: ["Đọc thành 'e' thường hoặc 'a' thuần Việt."],
      selfCheckTip: "Miệng mở rộng khoảng hai ngón tay xếp dọc.",
    },
    examples: [
      { word: "cat", ipa: "/kæt/", translation: "con mèo", position: "medial", highlightedLetters: "a" },
      { word: "apple", ipa: "/ˈæp.əl/", translation: "quả táo", position: "initial", highlightedLetters: "a" },
      { word: "black", ipa: "/blæk/", translation: "màu đen", position: "medial", highlightedLetters: "a" },
    ],
    spellingPatterns: [{ letters: "a", examples: ["cat", "map", "bag", "hand"] }],
    minimalPairs: [
      {
        targetWord: { word: "man", ipa: "/mæn/", translation: "đàn ông" },
        confusedWord: { word: "men", ipa: "/men/", translation: "những người đàn ông" },
        confusedSoundSymbol: "/e/",
      },
    ],
  },
  {
    id: "ah-short",
    symbol: "/ʌ/",
    name: "Short AH",
    vietnameseName: "Âm ă / ă-ă",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn ngắn",
    phoneticProperties: {
      length: "short",
      voicing: "voiced",
      tonguePosition: "Giữa - Sau",
      jawOpening: "Mở vừa (Open-mid)",
      lipShape: "Môi thả lỏng tự nhiên",
      summary: "Nguyên âm ngắn mở rộng vừa, âm giống chữ 'ă' hoặc 'ă' nhẹ.",
    },
    articulation: {
      steps: [
        "Mở miệng vừa phải.",
        "Lưỡi hạ hơi thấp tự nhiên.",
        "Bật âm dứt khoát ngắn gọn.",
      ],
      commonMistakes: ["Đọc thành 'a' quá dài hoặc 'ơ'."],
      selfCheckTip: "Giật cơ bụng nhẹ khi bật /ʌ/.",
    },
    examples: [
      { word: "cup", ipa: "/kʌp/", translation: "cái cốc", position: "medial", highlightedLetters: "u" },
      { word: "bus", ipa: "/bʌs/", translation: "xe buýt", position: "medial", highlightedLetters: "u" },
      { word: "sun", ipa: "/sʌn/", translation: "mặt trời", position: "medial", highlightedLetters: "u" },
      { word: "love", ipa: "/lʌv/", translation: "yêu thương", position: "medial", highlightedLetters: "o" },
    ],
    spellingPatterns: [
      { letters: "u", examples: ["cup", "bus", "run", "sun"] },
      { letters: "o / ou", examples: ["love", "come", "touch"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "cup", ipa: "/kʌp/", translation: "cái cốc" },
        confusedWord: { word: "cap", ipa: "/kæp/", translation: "mũ lưỡi trai" },
        confusedSoundSymbol: "/æ/",
      },
    ],
  },
  {
    id: "ar-long",
    symbol: "/ɑː/",
    name: "Long AR",
    vietnameseName: "Âm a dài",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn dài",
    phoneticProperties: {
      length: "long",
      voicing: "voiced",
      tonguePosition: "Sau (Back)",
      jawOpening: "Mở rộng (Open)",
      lipShape: "Môi mở tròn tự nhiên",
      summary: "Nguyên âm đơn dài, hạ hàm sâu, cuống lưỡi hạ thấp.",
    },
    articulation: {
      steps: [
        "Hạ hàm dưới xuống sâu tối đa thoải mái.",
        "Lưỡi đè thấp sát sàn miệng.",
        "Ngân âm 'aah' sâu trong cổ họng.",
      ],
      commonMistakes: ["Hạ hàm không đủ sâu."],
      selfCheckTip: "Khẩu hình giống bác sĩ khám họng bảo 'há miệng A'.",
    },
    examples: [
      { word: "car", ipa: "/kɑːr/", translation: "xe ô tô", position: "final", highlightedLetters: "ar" },
      { word: "father", ipa: "/ˈfɑː.ðər/", translation: "bố", position: "initial", highlightedLetters: "a" },
      { word: "start", ipa: "/stɑːt/", translation: "bắt đầu", position: "medial", highlightedLetters: "ar" },
    ],
    spellingPatterns: [
      { letters: "ar", examples: ["car", "park", "star", "hard"] },
      { letters: "a", examples: ["father", "fast", "class"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "heart", ipa: "/hɑːt/", translation: "trái tim" },
        confusedWord: { word: "hat", ipa: "/hæt/", translation: "cái mũ" },
        confusedSoundSymbol: "/æ/",
      },
    ],
  },
  {
    id: "o-short",
    symbol: "/ɒ/",
    name: "Short O",
    vietnameseName: "Âm o ngắn",
    category: "monophthong",
    typeLabel: "Nguyên âm đơn ngắn",
    phoneticProperties: {
      length: "short",
      voicing: "voiced",
      tonguePosition: "Sau (Back)",
      jawOpening: "Mở rộng (Open)",
      lipShape: "Môi tròn nhẹ",
      summary: "Nguyên âm ngắn Anh-Anh, hạ hàm sâu, môi tròn nhẹ.",
    },
    articulation: {
      steps: [
        "Hạ hàm xuống thấp.",
        "Môi tròn nhẹ.",
        "Bật âm ngắn dứt khoát 'o'.",
      ],
      commonMistakes: ["Nhầm sang âm /ɔː/ dài."],
      selfCheckTip: "Âm dứt khoát nhanh gọn.",
    },
    examples: [
      { word: "hot", ipa: "/hɒt/", translation: "nóng", position: "medial", highlightedLetters: "o" },
      { word: "box", ipa: "/bɒks/", translation: "hộp", position: "medial", highlightedLetters: "o" },
      { word: "stop", ipa: "/stɒp/", translation: "dừng lại", position: "medial", highlightedLetters: "o" },
    ],
    spellingPatterns: [{ letters: "o", examples: ["hot", "not", "dog", "box"] }],
    minimalPairs: [
      {
        targetWord: { word: "not", ipa: "/nɒt/", translation: "không" },
        confusedWord: { word: "note", ipa: "/nəʊt/", translation: "ghi chú" },
        confusedSoundSymbol: "/əʊ/",
      },
    ],
  },

  // ==================== NGUYÊN ÂM ĐÔI (8 DIPHTHONGS) ====================
  {
    id: "diphthong-ey",
    symbol: "/eɪ/",
    name: "Diphthong EY",
    vietnameseName: "Âm ei",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Nguyên âm đôi trượt từ /e/ sang /ɪ/.",
    },
    articulation: {
      steps: [
        "Bắt đầu với khẩu hình âm /e/ (mở vừa).",
        "Trượt nhẹ chuyển dần sang âm /ɪ/ (môi dẹt nhẹ, hàm khép bớt).",
        "Âm đầu dài và mạnh hơn âm sau.",
      ],
      commonMistakes: ["Đọc thành âm 'ê' cứng của tiếng Việt."],
      selfCheckTip: "Cảm nhận sự chuyển động khẩu hình mượt mà từ e sang i.",
    },
    examples: [
      { word: "day", ipa: "/deɪ/", translation: "ngày", position: "final", highlightedLetters: "ay" },
      { word: "make", ipa: "/meɪk/", translation: "làm", position: "medial", highlightedLetters: "a_e" },
      { word: "rain", ipa: "/reɪn/", translation: "mưa", position: "medial", highlightedLetters: "ai" },
    ],
    spellingPatterns: [
      { letters: "a_e", examples: ["make", "take", "name"] },
      { letters: "ai / ay", examples: ["rain", "day", "play"] },
    ],
    minimalPairs: [
      {
        targetWord: { word: "late", ipa: "/leɪt/", translation: "muộn" },
        confusedWord: { word: "let", ipa: "/let/", translation: "để cho" },
        confusedSoundSymbol: "/e/",
      },
    ],
  },
  {
    id: "diphthong-ai",
    symbol: "/aɪ/",
    name: "Diphthong AI",
    vietnameseName: "Âm ai",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Nguyên âm đôi trượt từ /a/ mở rộng sang /ɪ/.",
    },
    articulation: {
      steps: [
        "Mở miệng rộng khẩu hình âm /a/.",
        "Trượt khép miệng dẹt môi dần sang /ɪ/.",
      ],
      commonMistakes: ["Đọc âm cuối quá cứng."],
      selfCheckTip: "Chuyển khẩu hình từ mở rộng sang dẹt khép.",
    },
    examples: [
      { word: "my", ipa: "/maɪ/", translation: "của tôi", position: "final", highlightedLetters: "y" },
      { word: "time", ipa: "/taɪm/", translation: "thời gian", position: "medial", highlightedLetters: "i_e" },
      { word: "like", ipa: "/laɪk/", translation: "thích", position: "medial", highlightedLetters: "i_e" },
    ],
    spellingPatterns: [
      { letters: "i_e", examples: ["like", "time", "fine"] },
      { letters: "y", examples: ["my", "sky", "fly"] },
      { letters: "igh", examples: ["high", "night", "light"] },
    ],
    minimalPairs: [],
  },
  {
    id: "diphthong-oy",
    symbol: "/ɔɪ/",
    name: "Diphthong OY",
    vietnameseName: "Âm oi",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Trượt từ /ɔː/ tròn môi sang /ɪ/ dẹt môi.",
    },
    articulation: {
      steps: [
        "Bắt đầu với môi tròn /ɔː/.",
        "Trượt nhanh sang dẹt khép /ɪ/.",
      ],
      commonMistakes: ["Quên không nhô tròn môi ở âm đầu."],
      selfCheckTip: "Môi từ tròn biến thành mỉm cười dẹt.",
    },
    examples: [
      { word: "boy", ipa: "/bɔɪ/", translation: "cậu bé", position: "final", highlightedLetters: "oy" },
      { word: "coin", ipa: "/kɔɪn/", translation: "đồng xu", position: "medial", highlightedLetters: "oi" },
      { word: "voice", ipa: "/vɔɪs/", translation: "giọng nói", position: "medial", highlightedLetters: "oi" },
    ],
    spellingPatterns: [
      { letters: "oi", examples: ["coin", "voice", "oil"] },
      { letters: "oy", examples: ["boy", "toy", "joy"] },
    ],
    minimalPairs: [],
  },
  {
    id: "diphthong-oh",
    symbol: "/əʊ/",
    name: "Diphthong OH",
    vietnameseName: "Âm ơu",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Trượt từ schwa /ə/ sang /ʊ/.",
    },
    articulation: {
      steps: [
        "Mở miệng thả lỏng âm /ə/.",
        "Trượt tròn nhẹ môi sang /ʊ/.",
      ],
      commonMistakes: ["Phát âm thành 'ô' cứng."],
      selfCheckTip: "Âm trượt êm mềm mại.",
    },
    examples: [
      { word: "go", ipa: "/ɡəʊ/", translation: "đi", position: "final", highlightedLetters: "o" },
      { word: "home", ipa: "/həʊm/", translation: "nhà", position: "medial", highlightedLetters: "o_e" },
      { word: "boat", ipa: "/bəʊt/", translation: "con thuyền", position: "medial", highlightedLetters: "oa" },
    ],
    spellingPatterns: [
      { letters: "o_e", examples: ["home", "phone", "nose"] },
      { letters: "oa / ow", examples: ["boat", "coat", "know", "show"] },
    ],
    minimalPairs: [],
  },
  {
    id: "diphthong-ow",
    symbol: "/aʊ/",
    name: "Diphthong OW",
    vietnameseName: "Âm au",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Trượt từ /a/ mở rộng sang /ʊ/ tròn môi.",
    },
    articulation: {
      steps: [
        "Mở rộng miệng âm /a/.",
        "Trượt khép tròn môi sang /ʊ/.",
      ],
      commonMistakes: ["Khép môi quá sớm."],
      selfCheckTip: "Khẩu hình thu nhỏ dần.",
    },
    examples: [
      { word: "now", ipa: "/naʊ/", translation: "bây giờ", position: "final", highlightedLetters: "ow" },
      { word: "house", ipa: "/haʊs/", translation: "ngôi nhà", position: "medial", highlightedLetters: "ou" },
      { word: "out", ipa: "/aʊt/", translation: "ra ngoài", position: "initial", highlightedLetters: "ou" },
    ],
    spellingPatterns: [
      { letters: "ou", examples: ["house", "out", "cloud"] },
      { letters: "ow", examples: ["now", "cow", "town"] },
    ],
    minimalPairs: [],
  },
  {
    id: "diphthong-ear",
    symbol: "/ɪə/",
    name: "Diphthong EAR",
    vietnameseName: "Âm i-ơ",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Trượt từ /ɪ/ sang schwa /ə/.",
    },
    articulation: {
      steps: [
        "Đặt khẩu hình /ɪ/.",
        "Trượt thả lỏng về /ə/.",
      ],
      commonMistakes: ["Đọc thành 'ia' cứng."],
      selfCheckTip: "Âm thả lỏng về sau.",
    },
    examples: [
      { word: "ear", ipa: "/ɪər/", translation: "tai", position: "initial", highlightedLetters: "ear" },
      { word: "here", ipa: "/hɪər/", translation: "ở đây", position: "final", highlightedLetters: "ere" },
      { word: "near", ipa: "/nɪər/", translation: "gần", position: "medial", highlightedLetters: "ear" },
    ],
    spellingPatterns: [
      { letters: "ear", examples: ["ear", "near", "hear"] },
      { letters: "ere / eer", examples: ["here", "beer", "cheer"] },
    ],
    minimalPairs: [],
  },
  {
    id: "diphthong-air",
    symbol: "/eə/",
    name: "Diphthong AIR",
    vietnameseName: "Âm e-ơ",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Trượt từ /e/ sang schwa /ə/.",
    },
    articulation: {
      steps: [
        "Mở vừa khẩu hình /e/.",
        "Trượt thả lỏng về /ə/.",
      ],
      commonMistakes: ["Thiếu đuôi schwa."],
      selfCheckTip: "Chuyển mượt từ e thả lỏng.",
    },
    examples: [
      { word: "air", ipa: "/eər/", translation: "không khí", position: "initial", highlightedLetters: "air" },
      { word: "hair", ipa: "/heər/", translation: "tóc", position: "final", highlightedLetters: "air" },
      { word: "care", ipa: "/keər/", translation: "chăm sóc", position: "final", highlightedLetters: "are" },
    ],
    spellingPatterns: [
      { letters: "air", examples: ["air", "hair", "pair"] },
      { letters: "are / ear", examples: ["care", "share", "bear"] },
    ],
    minimalPairs: [],
  },
  {
    id: "diphthong-oor",
    symbol: "/ʊə/",
    name: "Diphthong UOR",
    vietnameseName: "Âm u-ơ",
    category: "diphthong",
    typeLabel: "Nguyên âm đôi",
    phoneticProperties: {
      voicing: "voiced",
      summary: "Trượt từ /ʊ/ sang schwa /ə/.",
    },
    articulation: {
      steps: [
        "Bắt đầu với môi hơi tròn /ʊ/.",
        "Mở môi thả lỏng về /ə/.",
      ],
      commonMistakes: ["Thay bằng âm /ɔː/ (xu hướng hiện đại)."],
      selfCheckTip: "Môi từ tròn thả lỏng phẳng.",
    },
    examples: [
      { word: "tour", ipa: "/tʊər/", translation: "chuyến du lịch", position: "final", highlightedLetters: "our" },
      { word: "pure", ipa: "/pjʊər/", translation: "tinh khiết", position: "final", highlightedLetters: "ure" },
      { word: "cure", ipa: "/kjʊər/", translation: "chữa trị", position: "final", highlightedLetters: "ure" },
    ],
    spellingPatterns: [
      { letters: "ure", examples: ["pure", "cure", "secure"] },
      { letters: "our", examples: ["tour"] },
    ],
    minimalPairs: [],
  },

  // ==================== PHỤ ÂM (24 CONSONANTS) ====================
  {
    id: "p-sound",
    symbol: "/p/",
    name: "P sound",
    vietnameseName: "Phụ âm P (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm bật hai môi",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Bật nổ (Plosive)",
      placeOfArticulation: "Hai môi (Bilabial)",
      summary: "Phụ âm vô thanh bật hơi từ hai môi ép chặt.",
    },
    articulation: {
      steps: [
        "Mím chặt hai môi lại nén luồng hơi.",
        "Bật mạnh hai môi ra thả luồng hơi thoát ra.",
        "Dây thanh không rung.",
      ],
      commonMistakes: ["Rung dây thanh âm thành /b/."],
      selfCheckTip: "Cầm tờ giấy trước miệng, âm /p/ làm giấy bật bay nhẹ.",
    },
    examples: [
      { word: "pen", ipa: "/pen/", translation: "bút", position: "initial", highlightedLetters: "p" },
      { word: "stop", ipa: "/stɒp/", translation: "dừng lại", position: "final", highlightedLetters: "p" },
      { word: "apple", ipa: "/ˈæp.əl/", translation: "quả táo", position: "medial", highlightedLetters: "pp" },
    ],
    spellingPatterns: [{ letters: "p / pp", examples: ["pen", "apple", "stop"] }],
    minimalPairs: [
      {
        targetWord: { word: "pat", ipa: "/pæt/", translation: "vỗ nhẹ" },
        confusedWord: { word: "bat", ipa: "/bæt/", translation: "gậy bóng chày" },
        confusedSoundSymbol: "/b/",
      },
    ],
  },
  {
    id: "b-sound",
    symbol: "/b/",
    name: "B sound",
    vietnameseName: "Phụ âm B (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm bật hai môi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Bật nổ (Plosive)",
      placeOfArticulation: "Hai môi (Bilabial)",
      summary: "Cặp hữu thanh của /p/, dây thanh rung khi bật môi.",
    },
    articulation: {
      steps: [
        "Mím hai môi nén hơi.",
        "Bật môi phát âm đồng thời rung dây thanh.",
      ],
      commonMistakes: ["Quên không rung dây thanh."],
      selfCheckTip: "Đặt tay lên cổ họng thấy rung nhẹ.",
    },
    examples: [
      { word: "big", ipa: "/bɪɡ/", translation: "to lớn", position: "initial", highlightedLetters: "b" },
      { word: "book", ipa: "/bʊk/", translation: "sách", position: "initial", highlightedLetters: "b" },
      { word: "cab", ipa: "/kæb/", translation: "xe taxi", position: "final", highlightedLetters: "b" },
    ],
    spellingPatterns: [{ letters: "b / bb", examples: ["big", "rabbit", "job"] }],
    minimalPairs: [],
  },
  {
    id: "t-sound",
    symbol: "/t/",
    name: "T sound",
    vietnameseName: "Phụ âm T (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm bật đầu lưỡi",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Bật nổ (Plosive)",
      placeOfArticulation: "Lợi (Alveolar)",
      summary: "Đầu lưỡi chạm chân răng trên nén hơi rồi bật ra vô thanh.",
    },
    articulation: {
      steps: [
        "Đặt đầu lưỡi vào phần lợi phía sau răng cửa trên.",
        "Bật đầu lưỡi xuống nhanh để luồng hơi thoát ra.",
        "Không rung cổ họng.",
      ],
      commonMistakes: ["Đọc thành 't' tiếng Việt bị bẹt."],
      selfCheckTip: "Bật luồng hơi mạnh dứt khoát.",
    },
    examples: [
      { word: "tea", ipa: "/tiː/", translation: "trà", position: "initial", highlightedLetters: "t" },
      { word: "cat", ipa: "/kæt/", translation: "con mèo", position: "final", highlightedLetters: "t" },
      { word: "water", ipa: "/ˈwɔː.tər/", translation: "nước", position: "medial", highlightedLetters: "t" },
    ],
    spellingPatterns: [{ letters: "t / tt", examples: ["tea", "little", "cat"] }],
    minimalPairs: [
      {
        targetWord: { word: "ten", ipa: "/ten/", translation: "số 10" },
        confusedWord: { word: "den", ipa: "/den/", translation: "hang thú" },
        confusedSoundSymbol: "/d/",
      },
    ],
  },
  {
    id: "d-sound",
    symbol: "/d/",
    name: "D sound",
    vietnameseName: "Phụ âm D (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm bật đầu lưỡi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Bật nổ (Plosive)",
      placeOfArticulation: "Lợi (Alveolar)",
      summary: "Cặp hữu thanh của /t/, đầu lưỡi bật khỏi lợi kèm rung cổ họng.",
    },
    articulation: {
      steps: [
        "Đặt đầu lưỡi lên chân răng trên.",
        "Bật lưỡi rung cổ họng.",
      ],
      commonMistakes: ["Đọc thành 'đ' quá nặng."],
      selfCheckTip: "Cổ họng rung khi bật đầu lưỡi.",
    },
    examples: [
      { word: "day", ipa: "/deɪ/", translation: "ngày", position: "initial", highlightedLetters: "d" },
      { word: "door", ipa: "/dɔːr/", translation: "cửa", position: "initial", highlightedLetters: "d" },
      { word: "bed", ipa: "/bed/", translation: "giường", position: "final", highlightedLetters: "d" },
    ],
    spellingPatterns: [{ letters: "d / dd", examples: ["day", "ladder", "red"] }],
    minimalPairs: [],
  },
  {
    id: "k-sound",
    symbol: "/k/",
    name: "K sound",
    vietnameseName: "Phụ âm K (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm bật cuống lưỡi",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Bật nổ (Plosive)",
      placeOfArticulation: "Ngạc mềm (Velar)",
      summary: "Cuống lưỡi nâng chạm ngạc mềm chặn hơi rồi bật ra vô thanh.",
    },
    articulation: {
      steps: [
        "Nâng cuống lưỡi chạm ngạc mềm (vòm miệng mềm phía sau).",
        "Bật mạnh cuống lưỡi xuống đẩy gió ra.",
      ],
      commonMistakes: ["Bật quá nhẹ ở cuối từ."],
      selfCheckTip: "Âm khặc nhẹ ở sâu trong họng.",
    },
    examples: [
      { word: "cat", ipa: "/kæt/", translation: "con mèo", position: "initial", highlightedLetters: "c" },
      { word: "key", ipa: "/kiː/", translation: "chìa khóa", position: "initial", highlightedLetters: "k" },
      { word: "book", ipa: "/bʊk/", translation: "sách", position: "final", highlightedLetters: "k" },
    ],
    spellingPatterns: [{ letters: "k / c / ck", examples: ["key", "cat", "black"] }],
    minimalPairs: [
      {
        targetWord: { word: "cap", ipa: "/kæp/", translation: "mũ" },
        confusedWord: { word: "gap", ipa: "/ɡæp/", translation: "khoảng trống" },
        confusedSoundSymbol: "/ɡ/",
      },
    ],
  },
  {
    id: "g-sound",
    symbol: "/ɡ/",
    name: "G sound",
    vietnameseName: "Phụ âm G (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm bật cuống lưỡi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Bật nổ (Plosive)",
      placeOfArticulation: "Ngạc mềm (Velar)",
      summary: "Cặp hữu thanh của /k/, cuống lưỡi bật kèm rung thanh quản.",
    },
    articulation: {
      steps: [
        "Nâng cuống lưỡi áp ngạc mềm.",
        "Bật cuống lưỡi phát âm rung giọng.",
      ],
      commonMistakes: ["Quên rung giọng thành /k/."],
      selfCheckTip: "Rung cổ họng khi phát /g/.",
    },
    examples: [
      { word: "go", ipa: "/ɡəʊ/", translation: "đi", position: "initial", highlightedLetters: "g" },
      { word: "get", ipa: "/ɡet/", translation: "lấy", position: "initial", highlightedLetters: "g" },
      { word: "bag", ipa: "/bæɡ/", translation: "túi", position: "final", highlightedLetters: "g" },
    ],
    spellingPatterns: [{ letters: "g / gg", examples: ["go", "egg", "big"] }],
    minimalPairs: [],
  },
  {
    id: "ch-sound",
    symbol: "/tʃ/",
    name: "CH sound",
    vietnameseName: "Phụ âm CH (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm tắc xát",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Tắc xát (Affricate)",
      placeOfArticulation: "Sau lợi (Post-alveolar)",
      summary: "Kết hợp bật /t/ và xát /ʃ/, chu môi vô thanh.",
    },
    articulation: {
      steps: [
        "Môi hơi chu tròn nhô trước.",
        "Đầu lưỡi chạm sau lợi bật nhẹ rồi xát hơi ra ngoài.",
      ],
      commonMistakes: ["Đọc thành 'ch' tiếng Việt phẳng."],
      selfCheckTip: "Môi chu tròn bật gió dứt khoát.",
    },
    examples: [
      { word: "cheese", ipa: "/tʃiːz/", translation: "pho mát", position: "initial", highlightedLetters: "ch" },
      { word: "church", ipa: "/tʃɜːtʃ/", translation: "nhà thờ", position: "initial", highlightedLetters: "ch" },
      { word: "watch", ipa: "/wɒtʃ/", translation: "đồng hồ", position: "final", highlightedLetters: "tch" },
    ],
    spellingPatterns: [{ letters: "ch / tch", examples: ["chair", "catch", "match"] }],
    minimalPairs: [
      {
        targetWord: { word: "chin", ipa: "/tʃɪn/", translation: "cằm" },
        confusedWord: { word: "gin", ipa: "/dʒɪn/", translation: "rượu gin" },
        confusedSoundSymbol: "/dʒ/",
      },
    ],
  },
  {
    id: "j-sound",
    symbol: "/dʒ/",
    name: "J sound",
    vietnameseName: "Phụ âm J (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm tắc xát",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Tắc xát (Affricate)",
      placeOfArticulation: "Sau lợi (Post-alveolar)",
      summary: "Cặp hữu thanh của /tʃ/, chu môi bật xát kèm rung cổ họng.",
    },
    articulation: {
      steps: [
        "Chu môi tròn nhẹ.",
        "Đầu lưỡi bật xát sau lợi kèm rung thanh quản mạnh.",
      ],
      commonMistakes: ["Quên rung thanh quản."],
      selfCheckTip: "Môi chu tròn rung cổ họng.",
    },
    examples: [
      { word: "job", ipa: "/dʒɒb/", translation: "công việc", position: "initial", highlightedLetters: "j" },
      { word: "jump", ipa: "/dʒʌmp/", translation: "nhảy", position: "initial", highlightedLetters: "j" },
      { word: "bridge", ipa: "/brɪdʒ/", translation: "cây cầu", position: "final", highlightedLetters: "dge" },
    ],
    spellingPatterns: [{ letters: "j / g / dge", examples: ["jam", "page", "bridge"] }],
    minimalPairs: [],
  },
  {
    id: "f-sound",
    symbol: "/f/",
    name: "F sound",
    vietnameseName: "Phụ âm F (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm xát răng môi",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Răng môi (Labiodental)",
      summary: "Răng cửa trên cắn nhẹ môi dưới đẩy luồng hơi vô thanh.",
    },
    articulation: {
      steps: [
        "Răng cửa trên chạm nhẹ vào viền trong môi dưới.",
        "Thổi hơi nhẹ qua kẽ răng môi mà không rung cổ họng.",
      ],
      commonMistakes: ["Mím hai môi lại như âm /p/."],
      selfCheckTip: "Cảm nhận hơi mát lướt qua môi dưới.",
    },
    examples: [
      { word: "fish", ipa: "/fɪʃ/", translation: "con cá", position: "initial", highlightedLetters: "f" },
      { word: "food", ipa: "/fuːd/", translation: "thức ăn", position: "initial", highlightedLetters: "f" },
      { word: "leaf", ipa: "/liːf/", translation: "chiếc lá", position: "final", highlightedLetters: "f" },
    ],
    spellingPatterns: [{ letters: "f / ff / ph", examples: ["fish", "off", "phone"] }],
    minimalPairs: [
      {
        targetWord: { word: "fan", ipa: "/fæn/", translation: "cái quạt" },
        confusedWord: { word: "van", ipa: "/væn/", translation: "xe tải nhỏ" },
        confusedSoundSymbol: "/v/",
      },
    ],
  },
  {
    id: "v-sound",
    symbol: "/v/",
    name: "V sound",
    vietnameseName: "Phụ âm V (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm xát răng môi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Răng môi (Labiodental)",
      summary: "Cặp hữu thanh của /f/, răng trên đặt lên môi dưới rung cổ họng.",
    },
    articulation: {
      steps: [
        "Răng trên chạm nhẹ môi dưới.",
        "Đẩy hơi đồng thời rung thanh quản làm môi dưới tê nhẹ.",
      ],
      commonMistakes: ["Đọc thành 'v' tiếng Việt không chạm răng."],
      selfCheckTip: "Môi dưới rung tê nhẹ.",
    },
    examples: [
      { word: "voice", ipa: "/vɔɪs/", translation: "giọng nói", position: "initial", highlightedLetters: "v" },
      { word: "van", ipa: "/væn/", translation: "xe tải", position: "initial", highlightedLetters: "v" },
      { word: "five", ipa: "/faɪv/", translation: "số 5", position: "final", highlightedLetters: "ve" },
    ],
    spellingPatterns: [{ letters: "v / ve", examples: ["van", "five", "save"] }],
    minimalPairs: [],
  },
  {
    id: "th-unvoiced",
    symbol: "/θ/",
    name: "Unvoiced TH",
    vietnameseName: "Phụ âm TH nhẹ (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm xát răng",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Giữa răng (Dental)",
      summary: "Đầu lưỡi đặt giữa hai hàm răng, thổi luồng hơi vô thanh.",
    },
    articulation: {
      steps: [
        "Đặt đầu lưỡi thè nhẹ ra giữa hai răng cửa.",
        "Thổi luồng hơi qua kẽ lưỡi và răng trên.",
        "Không rung dây thanh.",
      ],
      commonMistakes: ["Thè lưỡi không kịp đọc thành /t/ hoặc /s/."],
      selfCheckTip: "Nhìn gương thấy đầu lưỡi nhô ra giữa hai răng.",
    },
    examples: [
      { word: "think", ipa: "/θɪŋk/", translation: "suy nghĩ", position: "initial", highlightedLetters: "th" },
      { word: "thank", ipa: "/θæŋk/", translation: "cảm ơn", position: "initial", highlightedLetters: "th" },
      { word: "bath", ipa: "/bɑːθ/", translation: "bồn tắm", position: "final", highlightedLetters: "th" },
    ],
    spellingPatterns: [{ letters: "th", examples: ["think", "third", "bath"] }],
    minimalPairs: [
      {
        targetWord: { word: "think", ipa: "/θɪŋk/", translation: "suy nghĩ" },
        confusedWord: { word: "sink", ipa: "/sɪŋk/", translation: "bồn rửa" },
        confusedSoundSymbol: "/s/",
      },
    ],
  },
  {
    id: "th-voiced",
    symbol: "/ð/",
    name: "Voiced TH",
    vietnameseName: "Phụ âm TH mạnh (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm xát răng",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Giữa răng (Dental)",
      summary: "Cặp hữu thanh của /θ/, đầu lưỡi kẹp nhẹ răng rung thanh quản.",
    },
    articulation: {
      steps: [
        "Đặt đầu lưỡi giữa hai răng cửa.",
        "Rung thanh quản tạo âm ê tê nhẹ ở lưỡi.",
      ],
      commonMistakes: ["Đọc thành 'đ' hoặc 'z'."],
      selfCheckTip: "Đầu lưỡi tê nhẹ khi phát âm.",
    },
    examples: [
      { word: "this", ipa: "/ðɪs/", translation: "cái này", position: "initial", highlightedLetters: "th" },
      { word: "mother", ipa: "/ˈmʌð.ər/", translation: "mẹ", position: "medial", highlightedLetters: "th" },
      { word: "with", ipa: "/wɪð/", translation: "với", position: "final", highlightedLetters: "th" },
    ],
    spellingPatterns: [{ letters: "th", examples: ["this", "that", "mother"] }],
    minimalPairs: [],
  },
  {
    id: "s-sound",
    symbol: "/s/",
    name: "S sound",
    vietnameseName: "Phụ âm S (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm xát lợi",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Lợi (Alveolar)",
      summary: "Hai răng khép nhẹ, đầu lưỡi gần lợi thổi hơi rít vô thanh.",
    },
    articulation: {
      steps: [
        "Hai hàm răng khép gần nhau.",
        "Đầu lưỡi nâng gần lợi trên.",
        "Thổi luồng hơi xát rít ra kẽ răng.",
      ],
      commonMistakes: ["Chu môi quá đà thành /ʃ/."],
      selfCheckTip: "Môi dẹt dẹt tiếng gió xì.",
    },
    examples: [
      { word: "sun", ipa: "/sʌn/", translation: "mặt trời", position: "initial", highlightedLetters: "s" },
      { word: "sit", ipa: "/sɪt/", translation: "ngồi", position: "initial", highlightedLetters: "s" },
      { word: "bus", ipa: "/bʌs/", translation: "xe buýt", position: "final", highlightedLetters: "s" },
    ],
    spellingPatterns: [{ letters: "s / ss / c", examples: ["sun", "pass", "city"] }],
    minimalPairs: [
      {
        targetWord: { word: "sip", ipa: "/sɪp/", translation: "nhấp một ngụm" },
        confusedWord: { word: "zip", ipa: "/zɪp/", translation: "kéo khóa" },
        confusedSoundSymbol: "/z/",
      },
    ],
  },
  {
    id: "z-sound",
    symbol: "/z/",
    name: "Z sound",
    vietnameseName: "Phụ âm Z (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm xát lợi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Lợi (Alveolar)",
      summary: "Cặp hữu thanh của /s/, răng khép nhẹ thổi hơi kèm rung giọng con ong.",
    },
    articulation: {
      steps: [
        "Khẩu hình giống /s/.",
        "Rung thanh quản tạo tiếng vo ve.",
      ],
      commonMistakes: ["Không rung cổ họng làm biến thành /s/."],
      selfCheckTip: "Tiếng ve kêu rù rù ở cổ họng.",
    },
    examples: [
      { word: "zoo", ipa: "/zuː/", translation: "sở thú", position: "initial", highlightedLetters: "z" },
      { word: "zero", ipa: "/ˈzɪə.rəʊ/", translation: "số không", position: "initial", highlightedLetters: "z" },
      { word: "buzz", ipa: "/bʌz/", translation: "tiếng vo ve", position: "final", highlightedLetters: "zz" },
    ],
    spellingPatterns: [{ letters: "z / zz / s (cuối từ)", examples: ["zoo", "buzz", "is", "has"] }],
    minimalPairs: [],
  },
  {
    id: "sh-sound",
    symbol: "/ʃ/",
    name: "SH sound",
    vietnameseName: "Phụ âm SH nặng (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm xát sau lợi",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Sau lợi (Post-alveolar)",
      summary: "Chu môi tròn nhô trước, thân lưỡi nâng thổi hơi vô thanh 'suýt'.",
    },
    articulation: {
      steps: [
        "Chu tròn hai môi nhô ra phía trước.",
        "Thân lưỡi nâng cao về phía sau lợi.",
        "Thổi luồng hơi suýt mạnh xì ra ngoài.",
      ],
      commonMistakes: ["Không chu môi khiến âm dẹt thành /s/."],
      selfCheckTip: "Môi chu như khi ra hiệu 'suýt / giữ trật tự'.",
    },
    examples: [
      { word: "shoe", ipa: "/ʃuː/", translation: "giày", position: "initial", highlightedLetters: "sh" },
      { word: "ship", ipa: "/ʃɪp/", translation: "con tàu", position: "initial", highlightedLetters: "sh" },
      { word: "fish", ipa: "/fɪʃ/", translation: "con cá", position: "final", highlightedLetters: "sh" },
    ],
    spellingPatterns: [{ letters: "sh / ti / ci", examples: ["ship", "nation", "special"] }],
    minimalPairs: [
      {
        targetWord: { word: "shoe", ipa: "/ʃuː/", translation: "giày" },
        confusedWord: { word: "sue", ipa: "/suː/", translation: "kiện tụng" },
        confusedSoundSymbol: "/s/",
      },
    ],
  },
  {
    id: "zh-sound",
    symbol: "/ʒ/",
    name: "ZH sound",
    vietnameseName: "Phụ âm ZH nhẹ (Hữu thanh)",
    category: "consonant",
    typeLabel: "Phụ âm hữu thanh - Âm xát sau lợi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Sau lợi (Post-alveolar)",
      summary: "Cặp hữu thanh của /ʃ/, chu môi rung giọng mềm mại.",
    },
    articulation: {
      steps: [
        "Chu môi tròn như âm /ʃ/.",
        "Rung giọng thanh quản êm.",
      ],
      commonMistakes: ["Đọc cứng thành /dʒ/."],
      selfCheckTip: "Âm mượt rung như tiếng 'j' tiếng Pháp.",
    },
    examples: [
      { word: "vision", ipa: "/ˈvɪʒ.ən/", translation: "tầm nhìn", position: "medial", highlightedLetters: "si" },
      { word: "treasure", ipa: "/ˈtreʒ.ər/", translation: "kho báu", position: "medial", highlightedLetters: "s" },
      { word: "casual", ipa: "/ˈkæʒ.u.əl/", translation: "bình thường", position: "medial", highlightedLetters: "s" },
    ],
    spellingPatterns: [{ letters: "si / su / ge", examples: ["vision", "treasure", "garage"] }],
    minimalPairs: [],
  },
  {
    id: "h-sound",
    symbol: "/h/",
    name: "H sound",
    vietnameseName: "Phụ âm H (Vô thanh)",
    category: "consonant",
    typeLabel: "Phụ âm vô thanh - Âm xát thanh môn",
    phoneticProperties: {
      voicing: "voiceless",
      mannerOfArticulation: "Xát (Fricative)",
      placeOfArticulation: "Thanh môn (Glottal)",
      summary: "Thở hơi nhẹ qua khe thanh môn.",
    },
    articulation: {
      steps: [
        "Mở miệng tự nhiên theo nguyên âm đứng sau.",
        "Thở nhẹ luồng hơi qua cổ họng.",
      ],
      commonMistakes: ["Thắt cổ họng quá gắt."],
      selfCheckTip: "Như tiếng hà hơi ấm vào lòng bàn tay.",
    },
    examples: [
      { word: "hat", ipa: "/hæt/", translation: "cái mũ", position: "initial", highlightedLetters: "h" },
      { word: "home", ipa: "/həʊm/", translation: "nhà", position: "initial", highlightedLetters: "h" },
      { word: "hello", ipa: "/həˈləʊ/", translation: "xin chào", position: "initial", highlightedLetters: "h" },
    ],
    spellingPatterns: [{ letters: "h / wh", examples: ["hat", "who"] }],
    minimalPairs: [],
  },
  {
    id: "m-sound",
    symbol: "/m/",
    name: "M sound",
    vietnameseName: "Phụ âm M (Mũi)",
    category: "consonant",
    typeLabel: "Phụ âm mũi - Hai môi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Mũi (Nasal)",
      placeOfArticulation: "Hai môi (Bilabial)",
      summary: "Mím nhẹ hai môi, hơi thoát qua đường mũi kèm rung giọng.",
    },
    articulation: {
      steps: [
        "Mím nhẹ hai môi.",
        "Cho luồng hơi phát qua mũi 'ừm'.",
      ],
      commonMistakes: ["Mở môi sớm khi âm đứng cuối từ."],
      selfCheckTip: "Bịt mũi lại tiếng mmm bị ngắt.",
    },
    examples: [
      { word: "man", ipa: "/mæn/", translation: "đàn ông", position: "initial", highlightedLetters: "m" },
      { word: "make", ipa: "/meɪk/", translation: "làm", position: "initial", highlightedLetters: "m" },
      { word: "room", ipa: "/ruːm/", translation: "phòng", position: "final", highlightedLetters: "m" },
    ],
    spellingPatterns: [{ letters: "m / mm", examples: ["man", "summer", "room"] }],
    minimalPairs: [],
  },
  {
    id: "n-sound",
    symbol: "/n/",
    name: "N sound",
    vietnameseName: "Phụ âm N (Mũi)",
    category: "consonant",
    typeLabel: "Phụ âm mũi - Đầu lưỡi lợi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Mũi (Nasal)",
      placeOfArticulation: "Lợi (Alveolar)",
      summary: "Đầu lưỡi đè sát lợi trên, hơi thoát qua đường mũi.",
    },
    articulation: {
      steps: [
        "Áp đầu lưỡi sát chân răng trên.",
        "Đẩy hơi ra đường mũi 'ừn'.",
      ],
      commonMistakes: ["Hạ lưỡi quá sớm."],
      selfCheckTip: "Đầu lưỡi giữ nguyên trên lợi.",
    },
    examples: [
      { word: "now", ipa: "/naʊ/", translation: "bây giờ", position: "initial", highlightedLetters: "n" },
      { word: "name", ipa: "/neɪm/", translation: "tên", position: "initial", highlightedLetters: "n" },
      { word: "sun", ipa: "/sʌn/", translation: "mặt trời", position: "final", highlightedLetters: "n" },
    ],
    spellingPatterns: [{ letters: "n / nn / kn", examples: ["now", "funny", "know"] }],
    minimalPairs: [],
  },
  {
    id: "ng-sound",
    symbol: "/ŋ/",
    name: "NG sound",
    vietnameseName: "Phụ âm NG (Mũi cuống lưỡi)",
    category: "consonant",
    typeLabel: "Phụ âm mũi - Cuống lưỡi ngạc mềm",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Mũi (Nasal)",
      placeOfArticulation: "Ngạc mềm (Velar)",
      summary: "Cuống lưỡi nâng chặn khoang miệng, hơi thoát ra mũi.",
    },
    articulation: {
      steps: [
        "Nâng cuống lưỡi chạm ngạc mềm.",
        "Mở luồng hơi qua mũi rung giọng 'ng'.",
      ],
      commonMistakes: ["Bật thêm âm /g/ ở cuối 'sing-g'."].slice(0, 1),
      selfCheckTip: "Đầu lưỡi nằm ở sàn miệng.",
    },
    examples: [
      { word: "sing", ipa: "/sɪŋ/", translation: "hát", position: "final", highlightedLetters: "ng" },
      { word: "song", ipa: "/sɒŋ/", translation: "bài hát", position: "final", highlightedLetters: "ng" },
      { word: "think", ipa: "/θɪŋk/", translation: "suy nghĩ", position: "medial", highlightedLetters: "n" },
    ],
    spellingPatterns: [{ letters: "ng / nk", examples: ["sing", "king", "think"] }],
    minimalPairs: [
      {
        targetWord: { word: "thing", ipa: "/θɪŋ/", translation: "thứ" },
        confusedWord: { word: "thin", ipa: "/θɪn/", translation: "mỏng" },
        confusedSoundSymbol: "/n/",
      },
    ],
  },
  {
    id: "l-sound",
    symbol: "/l/",
    name: "L sound",
    vietnameseName: "Phụ âm L (Bên)",
    category: "consonant",
    typeLabel: "Phụ âm bên - Đầu lưỡi lợi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Bên (Lateral approximant)",
      placeOfArticulation: "Lợi (Alveolar)",
      summary: "Đầu lưỡi chạm lợi, luồng hơi thoát ra hai bên cạnh lưỡi.",
    },
    articulation: {
      steps: [
        "Chạm đầu lưỡi vào chân răng cửa trên.",
        "Cho luồng hơi chạy qua hai bên rìa lưỡi.",
      ],
      commonMistakes: ["Nhầm với âm /r/."],
      selfCheckTip: "Đầu lưỡi cố định trên lợi.",
    },
    examples: [
      { word: "light", ipa: "/laɪt/", translation: "ánh sáng", position: "initial", highlightedLetters: "l" },
      { word: "like", ipa: "/laɪk/", translation: "thích", position: "initial", highlightedLetters: "l" },
      { word: "ball", ipa: "/bɔːl/", translation: "quả bóng", position: "final", highlightedLetters: "ll" },
    ],
    spellingPatterns: [{ letters: "l / ll", examples: ["like", "ball", "yellow"] }],
    minimalPairs: [
      {
        targetWord: { word: "light", ipa: "/laɪt/", translation: "ánh sáng" },
        confusedWord: { word: "right", ipa: "/raɪt/", translation: "đúng" },
        confusedSoundSymbol: "/r/",
      },
    ],
  },
  {
    id: "r-sound",
    symbol: "/r/",
    name: "R sound",
    vietnameseName: "Phụ âm R (Uốn lưỡi)",
    category: "consonant",
    typeLabel: "Phụ âm tiếp cận - Cong lưỡi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Tiếp cận (Approximant)",
      placeOfArticulation: "Sau lợi (Post-alveolar)",
      summary: "Đầu lưỡi hơi cong ngược về sau nhưng không chạm vòm miệng.",
    },
    articulation: {
      steps: [
        "Cong đầu lưỡi ngược nhẹ về sau khoang miệng.",
        "Tuyệt đối không để đầu lưỡi chạm vào đâu.",
        "Môi hơi chu nhẹ rung giọng phát âm.",
      ],
      commonMistakes: ["Đầu lưỡi đánh chạm vòm thành 'r' rung."],
      selfCheckTip: "Lưỡi treo lơ lửng không rung chạm.",
    },
    examples: [
      { word: "red", ipa: "/red/", translation: "màu đỏ", position: "initial", highlightedLetters: "r" },
      { word: "run", ipa: "/rʌn/", translation: "chạy", position: "initial", highlightedLetters: "r" },
      { word: "rain", ipa: "/reɪn/", translation: "mưa", position: "initial", highlightedLetters: "r" },
    ],
    spellingPatterns: [{ letters: "r / rr / wr", examples: ["red", "sorry", "write"] }],
    minimalPairs: [],
  },
  {
    id: "w-sound",
    symbol: "/w/",
    name: "W sound",
    vietnameseName: "Phụ âm W (Bán nguyên âm môi)",
    category: "consonant",
    typeLabel: "Bán nguyên âm - Tròn môi",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Tiếp cận (Approximant)",
      placeOfArticulation: "Môi - Ngạc mềm (Labio-velar)",
      summary: "Chu tròn môi như /uː/ rồi mở nhanh sang nguyên âm sau.",
    },
    articulation: {
      steps: [
        "Chu môi thật tròn hẹp.",
        "Mở nhanh môi sang khẩu hình nguyên âm kế tiếp.",
      ],
      commonMistakes: ["Đọc thành 'v' cắn môi."],
      selfCheckTip: "Môi chu tròn không cắn răng.",
    },
    examples: [
      { word: "water", ipa: "/ˈwɔː.tər/", translation: "nước", position: "initial", highlightedLetters: "w" },
      { word: "win", ipa: "/wɪn/", translation: "chiến thắng", position: "initial", highlightedLetters: "w" },
      { word: "wet", ipa: "/wet/", translation: "ướt", position: "initial", highlightedLetters: "w" },
    ],
    spellingPatterns: [{ letters: "w / wh", examples: ["wet", "white", "where"] }],
    minimalPairs: [
      {
        targetWord: { word: "wet", ipa: "/wet/", translation: "ướt" },
        confusedWord: { word: "vet", ipa: "/vet/", translation: "bác sĩ thú y" },
        confusedSoundSymbol: "/v/",
      },
    ],
  },
  {
    id: "y-sound",
    symbol: "/j/",
    name: "Y sound",
    vietnameseName: "Phụ âm Y (Bán nguyên âm ngạc)",
    category: "consonant",
    typeLabel: "Bán nguyên âm - Ngạc cứng",
    phoneticProperties: {
      voicing: "voiced",
      mannerOfArticulation: "Tiếp cận (Approximant)",
      placeOfArticulation: "Ngạc cứng (Palatal)",
      summary: "Khẩu hình /iː/ lướt nhanh sang nguyên âm kế tiếp.",
    },
    articulation: {
      steps: [
        "Nâng lưỡi cao như âm /iː/.",
        "Mở nhanh lưỡi lướt sang nguyên âm tiếp theo.",
      ],
      commonMistakes: ["Đọc thành 'z' hoặc 'j' tiếng Việt."],
      selfCheckTip: "Lướt từ vị trí 'i' lướt đi.",
    },
    examples: [
      { word: "yes", ipa: "/jes/", translation: "có, vâng", position: "initial", highlightedLetters: "y" },
      { word: "you", ipa: "/juː/", translation: "bạn", position: "initial", highlightedLetters: "y" },
      { word: "yellow", ipa: "/ˈjel.əʊ/", translation: "màu vàng", position: "initial", highlightedLetters: "y" },
    ],
    spellingPatterns: [{ letters: "y / u", examples: ["yes", "young", "use", "unit"] }],
    minimalPairs: [],
  },
];

export function getIpaSoundById(id: string): IpaSound | undefined {
  return IPA_SOUNDS.find((s) => s.id === id);
}

export function getIpaSoundsByCategory(category: IpaSound["category"]): IpaSound[] {
  return IPA_SOUNDS.filter((s) => s.category === category);
}
