import type { DictResult } from "./dictionary-cache";

/**
 * Kho từ điển chuyên ngành Khoa học Máy tính, Hệ điều hành, Kiến trúc Máy tính & Học thuật
 * Nạp sẵn phiên âm IPA chuẩn quốc tế và nghĩa tiếng Việt tự nhiên để truy xuất 0ms.
 */
export const CORE_TECH_LEXICON: Record<string, DictResult> = {
  // --- Operating Systems & Hardware Architecture ---
  "operating system": { phonetic: "/ˈɑːpəreɪtɪŋ ˈsɪstəm/", translationVi: "hệ điều hành" },
  "superscalar": { phonetic: "/ˌsuːpərˈskeɪlər/", translationVi: "siêu vô hướng (xử lý nhiều lệnh cùng lúc)" },
  "throughput": { phonetic: "/ˈθruːpʊt/", translationVi: "thông lượng (lượng xử lý trên đơn vị thời gian)" },
  "clock cycle": { phonetic: "/klɑːk ˈsaɪkl/", translationVi: "chu kỳ xung nhịp" },
  "virtual memory": { phonetic: "/ˈvɜːrtʃuəl ˈmeməri/", translationVi: "bộ nhớ ảo" },
  "page fault": { phonetic: "/peɪdʒ fɔːlt/", translationVi: "lỗi trang bộ nhớ (page fault)" },
  "deadlock": { phonetic: "/ˈdedlɑːk/", translationVi: "bế tắc hệ thống (deadlock)" },
  "embedded system": { phonetic: "/ɪmˈbedɪd ˈsɪstəm/", translationVi: "hệ thống nhúng" },
  "bottleneck": { phonetic: "/ˈbɑːtlnek/", translationVi: "điểm nghẽn hiệu năng" },
  "device driver": { phonetic: "/dɪˈvaɪs ˈdraɪvər/", translationVi: "trình điều khiển thiết bị" },
  "interrupt handler": { phonetic: "/ˈɪntərʌpt ˈhændlər/", translationVi: "trình xử lý ngắt" },
  "concurrency": { phonetic: "/kənˈkɜːrənsi/", translationVi: "tính đồng thời" },
  "multithreading": { phonetic: "/ˌmʌltiˈθredɪŋ/", translationVi: "đa luồng" },
  "synchronization": { phonetic: "/ˌsɪŋkrənəˈzeɪʃn/", translationVi: "sự đồng bộ hóa" },
  "semaphore": { phonetic: "/ˈseməfɔːr/", translationVi: "cờ hiệu đồng bộ (semaphore)" },
  "mutex": { phonetic: "/ˈmjuːteks/", translationVi: "khóa loại trừ tương hỗ (mutex)" },
  "pipeline": { phonetic: "/ˈpaɪplaɪn/", translationVi: "đường ống xử lý lệnh (pipeline)" },
  "cache": { phonetic: "/kæʃ/", translationVi: "bộ nhớ đệm" },
  "cache hit": { phonetic: "/kæʃ hɪt/", translationVi: "trúng bộ nhớ đệm" },
  "cache miss": { phonetic: "/kæʃ mɪs/", translationVi: "trượt bộ nhớ đệm" },
  "kernel": { phonetic: "/ˈkɜːrnl/", translationVi: "nhân hệ điều hành" },
  "system call": { phonetic: "/ˈsɪstəm kɔːl/", translationVi: "lời gọi hệ thống" },
  "scheduling": { phonetic: "/ˈskedʒuːlɪŋ/", translationVi: "lập lịch tiến trình" },
  "paging": { phonetic: "/ˈpeɪdʒɪŋ/", translationVi: "phân trang bộ nhớ" },
  "segmentation": { phonetic: "/ˌseɡmenˈteɪʃn/", translationVi: "phân đoạn bộ nhớ" },
  "microcontroller": { phonetic: "/ˌmaɪkroʊkənˈtroʊlər/", translationVi: "vi điều khiển" },
  "register": { phonetic: "/ˈredʒɪstər/", translationVi: "thanh ghi CPU" },
  "compiler": { phonetic: "/kəmˈpaɪlər/", translationVi: "trình biên dịch" },
  "interpreter": { phonetic: "/ɪnˈtɜːrprətər/", translationVi: "trình thông dịch" },
  "runtime": { phonetic: "/ˈrʌntaɪm/", translationVi: "môi trường thực thi" },
  "firmware": { phonetic: "/ˈfɜːrmwer/", translationVi: "phần mềm nhúng cố định (firmware)" },

  // --- Software Engineering & Web Architecture ---
  "architecture": { phonetic: "/ˈɑːrkɪtektʃər/", translationVi: "kiến trúc hệ thống" },
  "latency": { phonetic: "/ˈleɪtnsi/", translationVi: "độ trễ mạng / hệ thống" },
  "bandwidth": { phonetic: "/ˈbændwɪdθ/", translationVi: "băng thông" },
  "middleware": { phonetic: "/ˈmɪdlwer/", translationVi: "phần mềm trung gian (middleware)" },
  "asynchronous": { phonetic: "/eɪˈsɪŋkrənəs/", translationVi: "bất đồng bộ" },
  "synchronous": { phonetic: "/ˈsɪŋkrənəs/", translationVi: "đồng bộ" },
  "scalability": { phonetic: "/ˌskeɪləˈbɪləti/", translationVi: "khả năng mở rộng" },
  "idempotent": { phonetic: "/ˌaɪdəmˈpoʊtnt/", translationVi: "tính lũy thỏa (idempotent)" },
  "payload": { phonetic: "/ˈpeɪloʊd/", translationVi: "dữ liệu tải / thân gói tin" },
  "endpoint": { phonetic: "/ˈendpɔɪnt/", translationVi: "điểm cuối API" },
  "authentication": { phonetic: "/ɔːˌθentɪˈkeɪʃn/", translationVi: "xác thực danh tính" },
  "authorization": { phonetic: "/ˌɔːθərəˈzeɪʃn/", translationVi: "phân quyền truy cập" },
  "serialization": { phonetic: "/ˌsɪriələˈzeɪʃn/", translationVi: "tuần tự hóa dữ liệu" },
  "deserialization": { phonetic: "/diːˌsɪriələˈzeɪʃn/", translationVi: "giải tuần tự hóa" },
  "refactoring": { phonetic: "/riːˈfæktərɪŋ/", translationVi: "tái cấu trúc mã nguồn" },
  "encapsulation": { phonetic: "/ɪnˌkæpsjuˈleɪʃn/", translationVi: "tính đóng gói" },
  "polymorphism": { phonetic: "/ˌpɑːliˈmɔːrfɪzəm/", translationVi: "tính đa hình" },
  "inheritance": { phonetic: "/ɪnˈherɪtəns/", translationVi: "tính kế thừa" },
  "abstraction": { phonetic: "/æbˈstrækʃn/", translationVi: "tính trừu tượng hóa" },
  "deployment": { phonetic: "/dɪˈplɔɪmənt/", translationVi: "triển khai phần mềm" },
  "immutable": { phonetic: "/ɪˈmjuːtəbl/", translationVi: "bất biến (không thể sửa đổi)" },
  "mutable": { phonetic: "/ˈmjuːtəbl/", translationVi: "khả biến (có thể sửa đổi)" },
  "dependency": { phonetic: "/dɪˈpendənsi/", translationVi: "sự phụ thuộc / thư viện phụ thuộc" },

  // --- Core Academic & Cognitive Verbs ---
  "appreciate": { phonetic: "/əˈpriːʃieɪt/", translationVi: "đánh giá cao, hiểu rõ giá trị" },
  "demonstrate": { phonetic: "/ˈdemənstreɪt/", translationVi: "chứng minh, thể hiện" },
  "incorporate": { phonetic: "/ɪnˈkɔːrpəreɪt/", translationVi: "kết hợp, đưa vào" },
  "facilitate": { phonetic: "/fəˈsɪlɪteɪt/", translationVi: "tạo điều kiện thuận lợi" },
  "eliminate": { phonetic: "/ɪˈlɪmɪneɪt/", translationVi: "loại bỏ hoàn toàn" },
  "quantize": { phonetic: "/ˈkwɑːntaɪz/", translationVi: "lượng tử hóa (nén số thực)" },
  "alleviate": { phonetic: "/əˈliːvieɪt/", translationVi: "làm giảm bớt, xoa dịu" },
  "accommodate": { phonetic: "/əˈkɑːmədeɪt/", translationVi: "đáp ứng, chứa được" },
  "comprehend": { phonetic: "/ˌkɑːmprɪˈhend/", translationVi: "thấu hiểu trọn vẹn" },
  "consolidate": { phonetic: "/kənˈsɑːlɪdeɪt/", translationVi: "củng cố, hợp nhất" },
  "differentiate": { phonetic: "/ˌdɪfəˈrenʃieɪt/", translationVi: "phân biệt, tạo sự khác biệt" },
  "implement": { phonetic: "/ˈɪmplɪment/", translationVi: "triển khai thực hiện" },
  "optimize": { phonetic: "/ˈɑːptɪmaɪz/", translationVi: "tối ưu hóa" },
  "mitigate": { phonetic: "/ˈmɪtɪɡeɪt/", translationVi: "giảm thiểu rủi ro / tác hại" },
  "substantiate": { phonetic: "/səbˈstænʃieɪt/", translationVi: "chứng minh bằng bằng chứng" },
  "scrutinize": { phonetic: "/ˈskruːtənaɪz/", translationVi: "xem xét kỹ lưỡng" },
  "orchestrate": { phonetic: "/ˈɔːrkɪstreɪt/", translationVi: "điều phối, sắp xếp tinh vi" },
  "reconcile": { phonetic: "/ˈrekənsaɪl/", translationVi: "đối chiếu, hòa giải" },
  "synthesize": { phonetic: "/ˈsɪnθəsaɪz/", translationVi: "tổng hợp thông tin" },
  "underpin": { phonetic: "/ˌʌndərˈpɪn/", translationVi: "làm nền tảng cốt lõi cho" },
};
